---
title: "project mta"
author: "blair pasarkar"
format: html
editor: visual
---


```{r}
mta_ridership <-
  read.csv("~/SDS 192/sds192-project1/MTA_Daily_Ridership_Data__2020_-_2025.csv",
         header = TRUE)
na.omit(mta_ridership)
```

```{r}
library(dplyr)
library(lubridate)
library(ggplot2)
```

```{r}
mta_ridership <- mta_ridership |>
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) |>
  mutate(Month = month(Date),
         Day = day(Date),
         Year = year(Date))
```

```{r}
ggplot(mta_ridership, aes(x = Date, y = Buses....of.Comparable.Pre.Pandemic.Day)) +
  geom_line(color = "darkgray", size = 0.4, alpha = 0.8) +  
  geom_point(size = 0.7, alpha = 0.5, color = "blue") +  
  scale_x_date(date_breaks = "6 months", date_labels = "%b %Y") + 
  labs(
    x = "Date",
    y = "% of Bus Ridership Compared to Pre-COVID",
    title = "Bus Ridership Throughout Post-COVID Era"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(face = "bold", size = 14)
  )
```

```{r}
mta_2020 <- mta_ridership |>
filter(Year == 2020) |>
  group_by(Month) |>
   summarize(
     Total_Traffic = sum(Bridges.and.Tunnels..Total.Traffic) / 1e6, 
     Traffic_Compared_Pre_Pandemic = mean(Bridges.and.Tunnels....of.Comparable.Pre.Pandemic.Day) * 100 
   ) |>
   pivot_longer(cols = c(Total_Traffic, Traffic_Compared_Pre_Pandemic),
                names_to = "Type", values_to = "Value")
 
 ggplot(mta_2020, aes(x = Month, y = Value, fill = Type)) +
   geom_bar(stat = "identity", position = "dodge") +
   labs(
     title = "Monthly Bus Ridership vs Bridge & Tunnel Traffic (2020)",
     x = "Month",
     y = "Value (Traffic in Millions &  % of Pre-Pandemic)", 
     caption = "eg 70 on the y axis equates to 70% for Traffic_Compared_Pre_Pandemic; eg 60 on the y axis equates to 60 million for Total_Traffic"
   ) +
   scale_x_continuous(breaks = 1:12, labels = month.abb) +
  theme_minimal()
```




```{r}
ggplot(mta_ridership, aes(x = Date, y = Buses..Total.Estimated.Ridership)) +
  geom_line(color = "red", size = 0.4, alpha = 0.8) +  
  geom_point(size = 0.7, alpha = 0.5, color = "black") +  
  scale_x_date(date_breaks = "6 months", date_labels = "%b %Y") + 
  labs(
    x = "Date",
    y = "Amount of Bus Riders",
    title = "Amount of Bus Ridership Throughout Post-COVID Era"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(face = "bold", size = 14)
  )
```


```{r}
ggplot(mta_ridership, aes(x = Buses....of.Comparable.Pre.Pandemic.Day)) +
  geom_histogram(fill = "pink", color = "white") + 
  labs(title = "Frequency of Bus Ridership Amounts",
       x = "Percent of Bus Ridership Compared to Pre-Pandemic Day",
       y= "Days Occured")+
  scale_x_continuous(breaks = seq(0,1, by=.10))
  theme(plot.title = element_text(size = 15, color = "purple"))
```
